linq2db/linq2db.EntityFrameworkCore

Source/LinqToDB.EntityFrameworkCore/ILinqToDBForEFTools.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.Tests/LinqToDB.EntityFrameworkCore.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.Tests/Models/AdventuresWorks/AdventureWorksContext.cs, Tests/LinqToDB.EntityFrameworkCore.Tests/ToolsTests.cs, Tests/LinqToDB.EntityFrameworkCore.Tests/ValueConversion/ConvertorTests.cs, Tests/LinqToDB.EntityFrameworkCore.Tests/ValueConversion/IEntity`1.cs, Tests/LinqToDB.EntityFrameworkCore.Tests/ValueConversion/IdValueConverterSelector.cs, Tests/LinqToDB.EntityFrameworkCore.Tests/ValueConversion/IdValueConverter`2.cs, Tests/LinqToDB.EntityFrameworkCore.Tests/ValueConversion/Id`2.cs, Tests/LinqToDB.EntityFrameworkCore.Tests/ValueConversion/SubDivision.cs
=> Added additional mapping for IValueConverterSelector

Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/ConvertorTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/IdValueConverterSelector.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/IdValueConverter`2.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/Id`2.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/SubDivision.cs
=> Fix #40 EF Core value converter selector support

Build/linq2db.Default.props, NuGet.config, NuGet/linq2db.EntityFrameworkCore.nuspec, Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Source/LinqToDB.EntityFrameworkCore/ILinqToDBForEFTools.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsDataConnection.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Source/LinqToDB.EntityFrameworkCore/linq2db.EntityFrameworkCore.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/NpgSqlTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs, azure-pipelines.yml
Global Query Filters support.
EF Core ChangeTracker support.
=> Added supporting latest features for linq2db 3.0.0-rc0.

Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Source/LinqToDB.EntityFrameworkCore/linq2db.EntityFrameworkCore.csproj, Tests/LinqToDB.EntityFrameworkCore.BaseTests/LinqToDB.EntityFrameworkCore.BaseTests.csproj, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/JsonConverTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/Northwind/NorthwindContext.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs
@Kirill-Maurin, could you please add more converter tests, maybe i have missed something?
=> Added support for ValueConverter. Preparing for 3.0.0.rc1 release.

Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsDataConnection.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs
Fixes #56 
@sdanyliv I've added two failing tests and a fix for one of them.  See issue #56 for notes.
=> Fix EnableChangeTracker and AsNoTracking support

Build/linq2db.Default.props, NuGet/linq2db.EntityFrameworkCore.nuspec, Source/LinqToDB.EntityFrameworkCore/Internal/EFCoreExpressionAttribute.cs, Source/LinqToDB.EntityFrameworkCore/Internal/LinqToDBForEFQueryProvider.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.ContextExtensions.cs, Source/LinqToDB.EntityFrameworkCore/linq2db.EntityFrameworkCore.csproj, azure-pipelines.yml
Changes are ready. Waiting for 3.1.2 release.
=> Updating to linq2db 3.1.2

Build/linq2db.Default.props, NuGet/linq2db.EntityFrameworkCore.nuspec, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsDataConnection.cs, Source/LinqToDB.EntityFrameworkCore/linq2db.EntityFrameworkCore.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/NpgSqlTests.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/AAA.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/Child.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/DataContextExtensions.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/Detail.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/Entity.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/Entity2Item.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/IHasId.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/Id.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/IdTests.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/IdValueConverter.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/Item.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/ModelBuilderExtensions.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/QueryableExtensions.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/StringExtensions.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/SubDetail.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/TypeExtensions.cs, azure-pipelines.yml
=> Improved ChangeTracker feeding. Improved ConnectionString retrieval for NpgSql

Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/IssueTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/IssueModel/Issue73Entity.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/IssueModel/IssueContext.cs
=> Fix for #73. Corrected navigation property mapping.

Build/linq2db.Default.props, NuGet/linq2db.EntityFrameworkCore.nuspec, azure-pipelines.yml
=> Release 5.0.1

Build/linq2db.Default.props, NuGet/linq2db.EntityFrameworkCore.nuspec, azure-pipelines.yml
=> Release 5.0.2

Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Source/LinqToDB.EntityFrameworkCore/linq2db.EntityFrameworkCore.csproj, Source/LinqToDB.EntityFrameworkCore/linq2db.EntityFrameworkCore.csproj.DotSettings, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Logging/TestLoggerProvider.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/TestUtils.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/NpgSqlTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/IssueTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/JsonConverTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/IssueModel/Issue73Entity.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/IssueModel/IssueContext.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/Northwind/NorthwindContext.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/QueryableExtensions.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs
Fixes #82
Fixes #87
Closes #88
=> Fixed found issues with integration.

Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/TestUtils.cs
- map `TraceLevel` -> `LogLevel` when logging
- extract `TraceInfoStep`, `IsAsync` to scope state
- make better use of message templates and capturing parameters in order to utilize structured-aware logging providers
=> Logging improvements

Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs
=> Fix for #103. Corrected expression tree transformation for IgnoreQueryFilters.

Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Source/LinqToDB.EntityFrameworkCore/Internal/LinqToDBForEFQueryProvider.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs
=> Fixed SO when correcting ExpressionTree.

Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/CategoriesMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/CustomerCustomerDemoMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/CustomerDemographicsMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/CustomersMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/EmployeeTerritoriesMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/EmployeesMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/OrderDetailsMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/OrderMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/ProductsMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/RegionMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/ShippersMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/SuppliersMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind.Mapping/TerritoriesMap.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/Northwind/NorthwindContext.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/SQLiteTests.cs, linq2db.EFCore.sln
=> Added additional Identity detection code. SQLite tests.

Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Logging/TestLogger.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/TestUtils.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/Models/NpgSqlEntities/EntityWithArrays.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/Models/NpgSqlEntities/NpgSqlEnititesContext.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/NpgSqlTests.cs
=> Fix for #132. Removed arrays from automatic conversion.

Source/LinqToDB.EntityFrameworkCore/linq2db.EntityFrameworkCore.csproj, azure-pipelines.yml
- enable sourcelink for package
- add snupkg publish to nuget
=> SourceLink support

Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Source/LinqToDB.EntityFrameworkCore/ILinqToDBForEFTools.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/Models/ForMapping/ForMappingContext.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs
Found way how to detect correctly identity columns.
=> Better convention handling.

Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Models/ForMapping/ForMappingContextBase.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Models/ForMapping/StringTypes.cs, Tests/LinqToDB.EntityFrameworkCore.PomeloMySql.Tests/ForMappingTests.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/ForMappingTests.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/ForMappingTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ForMappingTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/ForMapping/ForMappingContext.cs
=> Fix for #157. Improved DataType handling.

NuGet/linq2db.EntityFrameworkCore.nuspec, azure-pipelines.yml
no code changes, fix linq2db nuget reference
=> Release 6.6.1

Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs
=> Fixed unexpected extension evaluation.

Build/linq2db.Default.props, Directory.Packages.props, NuGet.config, NuGet/linq2db.EntityFrameworkCore.nuspec, Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBExtensionsAdapter.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFExtensions.Async.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsDataConnection.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/ForMappingTestsBase.cs, azure-pipelines.yml
=> [V3] updates + v4 migration

Build/linq2db.Default.props, Directory.Packages.props, NuGet.config, NuGet/linq2db.EntityFrameworkCore.nuspec, Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Source/LinqToDB.EntityFrameworkCore/Internal/EFCoreExpressionAttribute.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBExtensionsAdapter.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFExtensions.Async.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.Mapping.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsDataConnection.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.PomeloMySql.Tests/PomeloMySqlTests.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/Models/NpgSqlEntities/EntityWithXmin.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/Inheritance/InheritanceContext.cs, azure-pipelines.yml, linq2db.EFCore.sln
=> [V6] updates + v4 migration

Directory.Packages.props, Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Tests/LinqToDB.EntityFrameworkCore.FSharpTests/LinqToDB.EntityFrameworkCore.FSharpTests.fsproj, Tests/LinqToDB.EntityFrameworkCore.FSharpTests/Tests.fs, linq2db.EFCore.sln
Added test for https://github.com/linq2db/linq2db/issues/3743
=> FSharp issue with EFCoreExpressionAttribute or UseFSharpTypes

Directory.Packages.props, NuGet.config, NuGet/linq2db.EntityFrameworkCore.nuspec, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/Northwind.Mapping/ProductsMap.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs
=> Added Temporal tables support.

.editorconfig, Build/linq2db.Default.props, Build/linq2db.Tests.props, Directory.Build.props, Directory.Packages.props, NuGet/linq2db.EntityFrameworkCore.nuspec, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.Extensions.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Source/LinqToDB.EntityFrameworkCore/Properties/AssemblyInfo.cs, Source/LinqToDB.EntityFrameworkCore/linq2db.EntityFrameworkCore.csproj, Tests/Directory.Build.props, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Interceptors/TestEntityServiceInterceptor.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/LinqToDB.EntityFrameworkCore.BaseTests.csproj, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Logging/TestLogger.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Models/Northwind/NorthwindData.cs, Tests/LinqToDB.EntityFrameworkCore.FSharpTests/LinqToDB.EntityFrameworkCore.FSharpTests.fsproj, Tests/LinqToDB.EntityFrameworkCore.PomeloMySql.Tests/LinqToDB.EntityFrameworkCore.PomeloMySql.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/Models/NpgSqlEntities/EntityWithXmin.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/Id.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/TypeExtensions.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/Inheritance/InheritanceContext.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/IdValueConverterSelector.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/Id`2.cs, azure-pipelines.yml, linq2db.EFCore.sln
=> Build updates (v6)

.editorconfig, Build/linq2db.Default.props, Build/linq2db.Tests.props, Directory.Build.props, Directory.Packages.props, NuGet/linq2db.EntityFrameworkCore.nuspec, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.Extensions.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Source/LinqToDB.EntityFrameworkCore/Properties/AssemblyInfo.cs, Source/LinqToDB.EntityFrameworkCore/linq2db.EntityFrameworkCore.csproj, Tests/Directory.Build.props, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Interceptors/TestEntityServiceInterceptor.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/LinqToDB.EntityFrameworkCore.BaseTests.csproj, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Logging/TestLogger.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Models/Northwind/NorthwindData.cs, Tests/LinqToDB.EntityFrameworkCore.FSharpTests/LinqToDB.EntityFrameworkCore.FSharpTests.fsproj, Tests/LinqToDB.EntityFrameworkCore.PomeloMySql.Tests/LinqToDB.EntityFrameworkCore.PomeloMySql.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/Models/NpgSqlEntities/EntityWithXmin.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/Id.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/TypeExtensions.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/Inheritance/InheritanceContext.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/IdValueConverterSelector.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/Id`2.cs, azure-pipelines.yml, linq2db.EFCore.sln
=> Build updates (v5)

.editorconfig, Build/linq2db.Default.props, Build/linq2db.Tests.props, Directory.Build.props, Directory.Packages.props, NuGet/linq2db.EntityFrameworkCore.nuspec, Source/LinqToDB.EntityFrameworkCore/Internal/LinqToDBForEFQueryProvider.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.Extensions.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Source/LinqToDB.EntityFrameworkCore/Properties/AssemblyInfo.cs, Source/LinqToDB.EntityFrameworkCore/linq2db.EntityFrameworkCore.csproj, Tests/Directory.Build.props, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Interceptors/TestEntityServiceInterceptor.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/LinqToDB.EntityFrameworkCore.BaseTests.csproj, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Logging/TestLogger.cs, Tests/LinqToDB.EntityFrameworkCore.PomeloMySql.Tests/LinqToDB.EntityFrameworkCore.PomeloMySql.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/Models/NpgSqlEntities/EntityWithXmin.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/Id.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/ModelBuilderExtensions.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/TypeExtensions.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/JsonConverTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/IdValueConverterSelector.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/Id`2.cs, azure-pipelines.yml, linq2db.EFCore.sln
=> Build updates (v3)

.editorconfig, Build/linq2db.Default.props, Build/linq2db.Tests.props, Directory.Build.props, Directory.Packages.props, NuGet/linq2db.EntityFrameworkCore.nuspec, Source/LinqToDB.EntityFrameworkCore/Internal/LinqToDBOptionsExtension.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.Extensions.cs, Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Source/LinqToDB.EntityFrameworkCore/Properties/AssemblyInfo.cs, Source/LinqToDB.EntityFrameworkCore/linq2db.EntityFrameworkCore.csproj, Tests/Directory.Build.props, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Interceptors/TestEntityServiceInterceptor.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/LinqToDB.EntityFrameworkCore.BaseTests.csproj, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Logging/TestLogger.cs, Tests/LinqToDB.EntityFrameworkCore.PomeloMySql.Tests/LinqToDB.EntityFrameworkCore.PomeloMySql.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/Models/NpgSqlEntities/EntityWithXmin.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/NpgSqlTests.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/Id.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/ModelBuilderExtensions.cs, Tests/LinqToDB.EntityFrameworkCore.PostgreSQL.Tests/SampleTests/TypeExtensions.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests.csproj, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ToolsTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/IdValueConverterSelector.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ValueConversion/Id`2.cs, azure-pipelines.yml, linq2db.EFCore.sln
=> Build updates (v2)

Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Models/ForMapping/WithInheritance.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/TestsBase.cs, Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/SQLiteTests.cs
=> Add more ProviderName values support

Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Models/ForMapping/ForMappingContextBase.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Models/ForMapping/TypesTable.cs, Tests/LinqToDB.EntityFrameworkCore.BaseTests/Models/ForMapping/WithInheritance.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/ForMappingTests.cs, Tests/LinqToDB.EntityFrameworkCore.SqlServer.Tests/Models/ForMapping/ForMappingContext.cs
=> Fix Column MaxLength load

Directory.Packages.props, NuGet.config, NuGet/linq2db.EntityFrameworkCore.nuspec, README.md, Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs, azure-pipelines.yml
=> Release 8.0.0
